"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "en" | "am" | "om"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    return value || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

const translations = {
  en: {
    dashboard: "Dashboard",
    profile: "Profile",
    about: "About",
    expertise: "Areas of Expertise",
    experience: "Experience & Education",
    publications: "Publications",
    connect: "Connect",
    events: "Upcoming Events",
    announcements: "Announcements",
    staffDashboard: "Staff Dashboard",
    coeec: "COEEC",
    yearsOfExperience: "Years of Experience",
    publications_count: "Publications",
    projectsCompleted: "Projects Completed",
    areasOfExpertise: "Areas of Expertise",
    upcomingEvents: "Upcoming Events",
    downloadCV: "Download CV",
    speaker: "Speaker",
    contactAndCV: "Contact & CV",
    getInTouchOrDownload: "Get in touch or download CV",
    basicInformation: "Basic Information",
    fullName: "Full Name",
    professionalTitle: "Professional Title",
    department: "Department",
    role: "Role",
    profileImage: "Profile Image",
    officeLocation: "Office Location",
    email: "Email",
    phone: "Phone",
    cvUpload: "CV Upload",
    professionalDetails: "Professional Details",
    about_description: "About Description",
    selectOrCreate: "Select or Create Expertise",
    position: "Position",
    institution: "Institution/Organization",
    startYear: "Start Year",
    endYear: "End Year",
    presentCheckbox: "Present",
    shortDescription: "Short Description",
    degreeTitle: "Degree Title",
    yearCompleted: "Year Completed",
    timeline: "Timeline",
    title: "Title",
    publisher: "Publisher/Journal/Conference",
    year: "Year",
    link: "Link (Optional)",
    publicationList: "Publications",
    linkedin: "LinkedIn",
    googleScholar: "Google Scholar",
    researchGate: "ResearchGate",
    personalWebsite: "Personal Website",
    eventTitle: "Event Title",
    date: "Date",
    time: "Time",
    location: "Location",
    eventSpeaker: "Speaker/Host",
    eventDescription: "Description",
    eventImage: "Event Image Upload",
    announcementTitle: "Announcement Title",
    announcementBody: "Body/Message",
    category: "Category",
    general: "General",
    research: "Research",
    academic: "Academic",
    admin: "Admin",
    attachment: "Attachment (Optional)",
    saveChanges: "Save Changes",
    addMore: "Add More",
  },
  am: {
    dashboard: "ዳሽቦርድ",
    profile: "ፕሮፋይል",
    about: "ስለ",
    expertise: "ችሎታዎች",
    experience: "ልምድ እና ትምህርት",
    publications: "ህትመቶች",
    connect: "ግንኙነት",
    events: "ተመጣጣኝ ክስተቶች",
    announcements: "ማስታወቂያዎች",
    staffDashboard: "ሰራተኛ ዳሽቦርድ",
    coeec: "COEEC",
    yearsOfExperience: "የልምድ ዓመታት",
    publications_count: "ህትመቶች",
    projectsCompleted: "ተሳክተው የተጠናቀቁ ፕሮጀክቶች",
    areasOfExpertise: "የችሎታ ዘርፎች",
    upcomingEvents: "ተመጣጣኝ ክስተቶች",
    downloadCV: "CV ያውርዱ",
    speaker: "ተናጋሪ",
    contactAndCV: "ግንኙነት እና CV",
    getInTouchOrDownload: "ዝርዝር ለማወቅ ወይም CV ለማውረድ",
    basicInformation: "መሠረታዊ መረጃ",
    fullName: "ሙሉ ስም",
    professionalTitle: "ሙያዊ ርዕስ",
    department: "ክፍል",
    role: "ሚና",
    profileImage: "ፕሮፋይል ምስል",
    officeLocation: "ቢሮ ቦታ",
    email: "ኢሜይል",
    phone: "ስልክ",
    cvUpload: "CV ላክ",
    professionalDetails: "ሙያዊ ዝርዝሮች",
    about_description: "ስለ መግለጫ",
    selectOrCreate: "ይምረጡ ወይም ውሰድ",
    position: "ቦታ",
    institution: "ተቋም/ድርጅት",
    startYear: "ጀማሪ ዓመት",
    endYear: "መጨረሻ ዓመት",
    presentCheckbox: "አሁን",
    shortDescription: "አጭር መግለጫ",
    degreeTitle: "ዲግሪ ርዕስ",
    yearCompleted: "ተጠናቋ ዓመት",
    timeline: "የጊዜ መስመር",
    title: "ርዕስ",
    publisher: "ታተሞ/ጆርናል/ኮንፈረንስ",
    year: "ዓመት",
    link: "ሊንክ (አማራጭ)",
    publicationList: "ህትመቶች",
    linkedin: "LinkedIn",
    googleScholar: "Google Scholar",
    researchGate: "ResearchGate",
    personalWebsite: "ግላዊ ድር ጣቢያ",
    eventTitle: "ክስተት ርዕስ",
    date: "ቀን",
    time: "ጊዜ",
    location: "ቦታ",
    eventSpeaker: "ተናጋሪ/ስቴ",
    eventDescription: "መግለጫ",
    eventImage: "ክስተት ምስል ላክ",
    announcementTitle: "ማስታወቂያ ርዕስ",
    announcementBody: "መሰረታዊ/መልዕክት",
    category: "ምድብ",
    general: "አጠቃላይ",
    research: "ምርምር",
    academic: "ትምህርታዊ",
    admin: "አስተዳደር",
    attachment: "ተያያዥ ሰነድ (አማራጭ)",
    saveChanges: "ለውጦች ያስቀምጡ",
    addMore: "ተጨምር",
  },
  om: {
    dashboard: "Daashiboordii",
    profile: "Pirofaayilii",
    about: "Waa'ee",
    expertise: "Garee Beekumsa",
    experience: "Muuxannoo fi Barnoota",
    publications: "Maxxansoota",
    connect: "Walqunnamtii",
    events: "Taammiloota Dhufaa",
    announcements: "Beeksisa",
    staffDashboard: "Daashiboordii Hojjettoota",
    coeec: "COEEC",
    yearsOfExperience: "Waggaa Muuxannoo",
    publications_count: "Maxxansoota",
    projectsCompleted: "Projeektiwwan Xumuraman",
    areasOfExpertise: "Keessummaa Beekumsa",
    upcomingEvents: "Taammiloota Dhufaa",
    downloadCV: "CV Buusi",
    speaker: "Dubbiitootaa",
    contactAndCV: "Quunnamtii fi CV",
    getInTouchOrDownload: "Nu qunnamii yookaan CV buusi",
    basicInformation: "Odeeffannoo Ijoo",
    fullName: "Maqaa Guutuu",
    professionalTitle: "Teessoo Hojiiti",
    department: "Kutaa",
    role: "Gahee",
    profileImage: "Suuraa Pirofaayilii",
    officeLocation: "Iddoo Biiroo",
    email: "Imeelii",
    phone: "Bilbila",
    cvUpload: "CV Galchi",
    professionalDetails: "Odeeffannoo Hojiiti",
    about_description: "Ibsa Waa'ee",
    selectOrCreate: "Filadhu yookaan Uumi",
    position: "Sadarka",
    institution: "Instiitiyuutii/Orgaaniizeeshinii",
    startYear: "Waggaa Eegalaa",
    endYear: "Waggaa Xummuraa",
    presentCheckbox: "Ammaa",
    shortDescription: "Ibsa Gabaabaa",
    degreeTitle: "Maqaa Digrii",
    yearCompleted: "Waggaa Xumurame",
    timeline: "Seensa Yeroo",
    title: "Maqaa",
    publisher: "Maqaa Maxxansaa/Joornalii/Koongiresii",
    year: "Waggaa",
    link: "Liinkii (Filannoo)",
    publicationList: "Maxxansoota",
    linkedin: "LinkedIn",
    googleScholar: "Google Scholar",
    researchGate: "ResearchGate",
    personalWebsite: "Website Dhuunfaa",
    eventTitle: "Maqaa Taammilaa",
    date: "Guyyaa",
    time: "Sa'a",
    location: "Iddoo",
    eventSpeaker: "Dubbiitootaa/Host",
    eventDescription: "Ibsa",
    eventImage: "Suuraa Taammilaa Galchi",
    announcementTitle: "Maqaa Beeksisaa",
    announcementBody: "Qabiyyee",
    category: "Garee",
    general: "Waliigala",
    research: "Qorannoo",
    academic: "Barnootaa",
    admin: "Bulchiinsa",
    attachment: "Fayyadama (Filannoo)",
    saveChanges: "Jijjiirama Olkaa'i",
    addMore: "Dabalata"
  }
}
